### PR TITLE
Remove docs from master in favor of a github-pages branch

### PR DESCRIPTION
**Pull request by jeddeloh**
I don't know if this is a bad idea, but building and committing the docs on master is kinda noisy. There are probably other solutions to this problem, but for now I propose we try having docs on a separate `github-pages` branch and see how it goes.

### CODE REVIEW

**Comment by jfrolich** [comment]
why is it a problem?

**Comment by jeddeloh** [comment]
> why is it a problem?
The problem with having a separate `github-pages` branch for documentation? I don't know. Not much? You have to make separate PRs when changing stuff and explain where the docs exist?

**Comment by jeddeloh** [comment]
Or are you referring to the noise from documentation? Maybe it's not a problem. Thoughts? I also thought I might do an automatic `docusaurus deploy` and it might be nicer to be doing that stuff in another branch?

**Comment by jeddeloh** [comment]
Actually, I'm going to close this. Instead, I think I'd like to keep the docs here in master and have an auto `docusaurus deploy` push to `github-pages` branch. Don't know when I'll get to that, though :)

**Comment by jfrolich** [comment]
Yeah my in my experience it's nicer in master because if you go back in history the docs are also kind of in sync :) It would also be easier to version docs if they are in the same branch.

**Pull request closed without merging**
